name: tf-tm
services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 8002:8000
#    volumes:
#      - .:/app
#    depends_on:
#      - db
  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_DB: tf-tm-dev-db
      POSTGRES_USER: tf-dev
      POSTGRES_PASSWORD: tf-dev
    ports:
      - 8003:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  default:
    name: tf-network
    external: true

volumes:
  postgres_data:
    driver: local
