services:
  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: tf-tm-dev-db
      POSTGRES_USER: tf-dev
      POSTGRES_PASSWORD: tf-dev
    ports:
      - "8001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
    postgres_data:
      driver: local
