# Generated by Django 5.0.4 on 2024-05-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_roles_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='ok', max_length=100),
            preserve_default=False,
        ),
    ]
