# Generated by Django 5.0.4 on 2024-05-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_task_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='roles',
            new_name='role',
        ),
    ]
