# Generated by Django 5.0.6 on 2024-05-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_created_by_updated_by_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
