# Generated by Django 5.0.6 on 2024-05-31 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberSerializer',
            new_name='Member',
        ),
    ]
