# Generated by Django 5.0.6 on 2024-05-31 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_uuid'),
    ]

    operations = [
        migrations.DeleteModel(name='User',),
    ]
